package: relation_select
version: '1.1.0'
author: Your Name
supportpage: https://github.com/your/repo

page:
    title: Relation Select
    icon: rex-icon fa-exchange

requires:
    redaxo: '^5.17'
    php:
        version: '>=8.1'
