package: relation_select
version: '1.3.2'
author: Friends of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/relation_select

page:
    title: Relation Select
    icon: rex-icon fa-exchange

requires:
    redaxo: '^5.17'
    php:
        version: '>=8.2'
